spring.application.name=cinescore

spring.datasource.url=jdbc:mysql://localhost:3306/cinescore
spring.datasource.username=root
spring.datasource.password=123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.open-in-view=false
jwt.secret=cinescore-chave-secreta-2026
jwt.expiration=86400000
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
